Models/Scenario.cs
using System.ComponentModel.DataAnnotations;

namespace UEFASwissFormatSelector.Models
{
    public class Scenario : Identifiable
    {
        [Display(Name = "Number of pots")]
        [Range(1, int.MaxValue)]
        public int NumberOfPot { get; set; }
        [Display(Name = "Number of Teams in a pot")]
        [Range(1, int.MaxValue)]
        public int NumberOfTeamsPerPot { get; set; }
        [Display(Name = "Number of Opponents from a pot")]
        [Range(1, int.MaxValue)]
        public int NumberOfGamesPerPot { get; set; }
        [Display(Name = "Play Each Match Home and Away")]
        public bool HomeAndAwayPerOpponent { get; set; }
    }
}

Controllers/ScenarioController.cs
using Microsoft.AspNetCore.Mvc;
using UEFASwissFormatSelector.Models;
using UEFASwissFormatSelector.Services;
using UEFASwissFormatSelector.ViewModels;

namespace UEFASwissFormatSelector.Controllers
{
    public class ScenarioController : Controller
    {
        private readonly IRepository repository;

        public ScenarioController(IRepository repository)
        {
            this.repository = repository;
        }
        
        public IActionResult Index()
        {
            return View(repository.Scenarios);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Scenario scenario)
        {
            if (ModelState.IsValid)
            {
                var similarScenario = repository.Scenarios.FirstOrDefault(s => s.NumberOfTeamsPerPot == scenario.NumberOfTeamsPerPot && s.NumberOfPot == scenario.NumberOfPot && s.NumberOfGamesPerPot == scenario.NumberOfGamesPerPot && s.HomeAndAwayPerOpponent == scenario.HomeAndAwayPerOpponent );
                if (similarScenario != null)
                {
                    ModelState.AddModelError("", "Similar scenario is already existing");
                    return View(scenario);
                }
                (repository.Scenarios as List<Scenario>)?.Add(scenario);
                return RedirectToAction(nameof(Index));
            }
            return View(scenario);
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var scenario = repository.Scenarios.ToList().Find(c => c.Id == id);
            if (scenario == null)
                RedirectToAction(nameof(Index));
            return View(scenario);
        }
        [HttpPost]
        public IActionResult Edit(Scenario scenario)
        {
            if (ModelState.IsValid)
            {
                var dbScenario = repository.Scenarios.FirstOrDefault(c => c.Id == scenario.Id);
                if (dbScenario != null)
                    dbScenario.Name = scenario.Name;
                return RedirectToAction(nameof(Index));
            }
            return View(scenario);
        }
    }
}

Controllers/ScenarioInstanceController.cs
using Microsoft.AspNetCore.Mvc;
using UEFASwissFormatSelector.Models;
using UEFASwissFormatSelector.Services;
using UEFASwissFormatSelector.ViewModels;

namespace UEFASwissFormatSelector.Controllers
{
    public class ScenarioInstanceController : Controller
    {
        private readonly IRepository repository;
        private readonly IMatchDrawService matchDrawService;

        public ScenarioInstanceController(IRepository repository, IMatchDrawService matchDrawService)
        {
            this.repository = repository;
            this.matchDrawService = matchDrawService;
        }        
        [HttpGet]
        public IActionResult Index()
        {
            return View(repository.ScenarioInstances);
        }
        [HttpGet]
        public IActionResult Add(Guid scenarioId)
        {
            var scenario = repository.Scenarios.FirstOrDefault(s => s.Id == scenarioId);
            if (scenario == null)
                return RedirectToAction(nameof(Index), nameof(Scenario));
            var viewModel = new AddScenarioInstanceViewModel();
            viewModel.Scenario = scenario;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Add(AddScenarioInstanceViewModel instanceVM)
        {
            if (ModelState.IsValid)
            {
                var scenario = repository.Scenarios.FirstOrDefault(s => s.Id == instanceVM.Scenario.Id);
                if (scenario == null)
                    return RedirectToAction(nameof(Index), nameof(Scenario));
                var instance = new ScenarioInstance(scenario)
                {
                    Name = instanceVM.Name
                };
                (repository.ScenarioInstances as List<ScenarioInstance>)?.Add(instance);
                return RedirectToAction(nameof(Index));
            }
            return View(instanceVM);
        }
        [HttpGet]
        public IActionResult Edit(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            var viewModel = new EditScenarioInstanceViewModel
            {
                InstanceId = scenarioInstance.Id,
                Scenario = scenarioInstance.Scenario,
                Name = scenarioInstance.Name
            };
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(EditScenarioInstanceViewModel instanceVM)
        {
            if (ModelState.IsValid)
            {
                var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == instanceVM.InstanceId);
                if (scenarioInstance != null)
                    scenarioInstance.Name = instanceVM.Name;
                return RedirectToAction(nameof(Index));
            }
            return View(instanceVM);
        }
        [HttpGet]
        //public IActionResult Explore(Guid scenarioInstanceId, ExploreScenarioInstanceViewModel? vm = null)
        //{
        //    var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
        //    if (scenarioInstance == null)
        //        return RedirectToAction(nameof(Index));
        //    ExploreScenarioInstanceViewModel viewModel;
        //    if (vm == null)
        //    {
        //        viewModel = GenerateVM(scenarioInstance);
        //    }
        //    else
        //    {
        //        viewModel = vm as ExploreScenarioInstanceViewModel;
        //    }

        //    return View(viewModel);
        //}
        public IActionResult Explore(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            var viewModel = new ExploreScenarioInstanceViewModel
            {
                Id = scenarioInstance.Id,
                Scenario = scenarioInstance.Scenario,
                Name = scenarioInstance.Name,
                ClubsInScenarioInstance = scenarioInstance.ClubsInScenarioInstance,
                Pots = scenarioInstance.Pots,
                Opponents = scenarioInstance.Opponents,
                MatchUps = scenarioInstance.MatchUps,
                MatchUpSkeleton = scenarioInstance.MatchUpSkeleton
            };
            if (!viewModel.ClubsInScenarioInstance.Any(c => c == null))
                foreach (var club in viewModel.ClubsInScenarioInstance)
                {
                    club.Club = repository.Clubs.FirstOrDefault(c => c.Id == club.ClubId);
                }
            return View(viewModel);
        }

        //private ExploreScenarioInstanceViewModel GenerateVM(ScenarioInstance scenarioInstance)
        //{
        //    ExploreScenarioInstanceViewModel viewModel = new ExploreScenarioInstanceViewModel
        //    {
        //        Id = scenarioInstance.Id,
        //        Scenario = scenarioInstance.Scenario,
        //        Name = scenarioInstance.Name,
        //        ClubsInScenarioInstance = scenarioInstance.ClubsInScenarioInstance,
        //        Pots = scenarioInstance.Pots
        //    };
        //    if (!viewModel.ClubsInScenarioInstance.Any(c => c == null))
        //        foreach (var club in viewModel.ClubsInScenarioInstance)
        //        {
        //            club.Club = repository.Clubs.FirstOrDefault(c => c.Id == club.ClubId);
        //        }

        //    return viewModel;
        //}

        [HttpGet]
        public IActionResult AddClubs(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            var viewModel = new List<SelectViewModel>();
            foreach (Club club in repository.Clubs)
            {
                viewModel.Add(new SelectViewModel
                {
                    Id = club.Id,
                    Name = club.Name
                });
            }
            ViewBag.scenarioInstanceId = scenarioInstanceId;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddClubs(List<SelectViewModel> selections, Guid scenarioInstanceId)
        {
            if (ModelState.IsValid)
            {
                var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
                if (scenarioInstance == null)
                    return RedirectToAction(nameof(Index));
                var checkedSelections = selections.Where(s => s.IsSelected).ToList();
                int expectedSelections = scenarioInstance.Scenario.NumberOfPot * scenarioInstance.Scenario.NumberOfTeamsPerPot;
                int actualSelections = checkedSelections.Count();
                if (actualSelections != expectedSelections)
                {
                    ViewBag.scenarioInstanceId = scenarioInstanceId;
                    ModelState.AddModelError(string.Empty, $"You have selected {actualSelections} instead of {expectedSelections}");
                    return View(selections);
                }
                var clubsInInstance = new List<ClubInScenarioInstance>();
                foreach (var item in checkedSelections)
                {
                    clubsInInstance.Add( new ClubInScenarioInstance(item.Id, scenarioInstanceId)
                    {
                        Club = repository.Clubs.FirstOrDefault(c=> c.Id == item.Id)
                    });
                }
                scenarioInstance.ClubsInScenarioInstance = clubsInInstance;
                return RedirectToAction(nameof(Explore), new { scenarioInstanceId = scenarioInstanceId });
            }
            return View(selections);
        }
        [HttpGet]
        public IActionResult RankClubs(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            ViewBag.scenarioInstanceId = scenarioInstanceId;
            var viewModel = scenarioInstance.ClubsInScenarioInstance;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult RankClubs(IEnumerable<ClubInScenarioInstance> model, Guid scenarioInstanceId)
        {
            if (ModelState.IsValid)
            {
                var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
                if (scenarioInstance == null)
                    return RedirectToAction(nameof(Index));
                scenarioInstance.ClubsInScenarioInstance = model;
                return RedirectToAction(nameof(Explore), new { scenarioInstanceId = scenarioInstanceId });
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult PotClubs(IEnumerable<ClubInScenarioInstance> model, Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            scenarioInstance.Pots = matchDrawService.PotTeam(scenarioInstance);
            return RedirectToAction(nameof(Explore), new { scenarioInstanceId = scenarioInstanceId });
        }
        [HttpGet]
        public IActionResult GenerateOponents(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)

Views/Scenario/Add.cshtml
@model Scenario
@{
    ViewData["Title"] = "Register a scenario";
}
<form asp-action="Add" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="mb-3 row">
        <label asp-for="Name" class="col-sm-1 col-form-label"></label>
        <div class="col-sm-2">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <label asp-for="NumberOfPot" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="NumberOfPot" class="form-control" />
            <span asp-validation-for="NumberOfPot" class="text-danger"></span>
        </div>
        <label asp-for="HomeAndAwayPerOpponent" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1 form-check mt-auto">
            <input asp-for="HomeAndAwayPerOpponent" class="form-check-input bg-primary" />
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="NumberOfTeamsPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="NumberOfTeamsPerPot" class="form-control" />
            <span asp-validation-for="NumberOfTeamsPerPot" class="text-danger"></span>
        </div>
        <label asp-for="NumberOfGamesPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="NumberOfGamesPerPot" class="form-control" />
            <span asp-validation-for="NumberOfGamesPerPot" class="text-danger"></span>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Register</button>
    </div>
</form>

Views/Scenario/Edit.cshtml
@model Scenario
@{
    ViewData["Title"] = $"Edit {Model.Name}";
}
<form asp-action="Edit" method="post">
    <input hidden asp-for="Id"/>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="mb-3 row">
        <label asp-for="Name" class="col-sm-1 col-form-label"></label>
        <div class="col-sm-2">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <label asp-for="NumberOfPot" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="NumberOfPot" class="form-control" readonly/>
            <span asp-validation-for="NumberOfPot" class="text-danger"></span>
        </div>
        <label asp-for="HomeAndAwayPerOpponent" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1 form-check mt-auto">
            <input asp-for="HomeAndAwayPerOpponent" class="form-check-input bg-primary" disabled />
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="NumberOfTeamsPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="NumberOfTeamsPerPot" class="form-control" readonly />
            <span asp-validation-for="NumberOfTeamsPerPot" class="text-danger"></span>
        </div>
        <label asp-for="NumberOfGamesPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="NumberOfGamesPerPot" class="form-control" readonly />
            <span asp-validation-for="NumberOfGamesPerPot" class="text-danger"></span>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>

Views/Scenario/Index.cshtml
@model IEnumerable<Scenario>
@{
    ViewData["Title"] = "List of Registered Scenarios";
}
@if(Model != null && Model.Count() > 0)
{
    int i = 1;
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>SN</th>
                <th>Scenario</th>
                <th>Pots</th>
                <th>Teams per pot</th>
                <th>Games per pot</th>
                <th>Home and Away</th>
                <th>***</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var scenario in Model)
            {
                <tr>
                    <td>@(i++)</td>
                    <td>@scenario.Name</td>
                    <td>@scenario.NumberOfPot</td>
                    <td>@scenario.NumberOfTeamsPerPot</td>
                    <td>@scenario.NumberOfGamesPerPot</td>
                    <td>@(scenario.HomeAndAwayPerOpponent? "Yes" : "No")</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@scenario.Id">Edit</a>
                        <a class="btn btn-primary" asp-action="Add" asp-controller="ScenarioInstance" asp-route-scenarioId="@scenario.Id">Create Simulation</a>
                    </td>
                </tr>                
            }
        </tbody>
    </table>    
}
else
{
    <h4 class="display-4">No club to display at the moment</h4>
}
<a class="btn btn-primary" asp-action="Add">Add Scenario</a>