Models/ScenarioInstance.cs
namespace UEFASwissFormatSelector.Models
{
    public class ScenarioInstance: Identifiable
    {
        public Guid ScenarioId { get; set; }
        public virtual Scenario Scenario { get; set; }
        public virtual IEnumerable<Pot> Pots { get; set; }
        public virtual IEnumerable<ClubInScenarioInstance> ClubsInScenarioInstance { get; set; }
        public Dictionary<Guid, IEnumerable<Pot>>? Opponents { get; set; }
        public Dictionary<Guid, List<Club>>? MatchUps { get; set; }
        public Dictionary<Guid, List<String>>? MatchUpSkeleton { get; set; }
        public ScenarioInstance(Scenario scenario)
        {
            Scenario = scenario;
            ScenarioId = scenario.Id;
            Pots = new Pot[scenario.NumberOfPot];
            ClubsInScenarioInstance = new ClubInScenarioInstance[scenario.NumberOfPot * scenario.NumberOfTeamsPerPot];
        }
        /// <summary>
        /// To be used only for db purpose
        /// </summary>
        public ScenarioInstance()
        {
            
        }
    }
}

Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using UEFASwissFormatSelector.Models;
using UEFASwissFormatSelector.Services;

namespace UEFASwissFormatSelector.Controllers
{
    public class ClubController : Controller
    {
        private IRepository _repository;
        public ClubController(IRepository repository)
        {
            _repository = repository;
        }        
        [HttpGet]
        public IActionResult Index()
        {            
            return View(_repository.Clubs);
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Countries = _repository.Countries;
            return View();
        }
        [HttpPost]
        public IActionResult Add(Club club)
        {
            if (ModelState.IsValid)
            {
                (_repository.Clubs as List<Club>)?.Add(club);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Countries = _repository.Countries;
            return View(club);
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var club = _repository.Clubs.ToList().Find(c => c.Id == id);
            if (club == null)
            {
                RedirectToAction(nameof(Index));
            }
            ViewBag.Countries = _repository.Countries;
            return View(club);
        }
        [HttpPost]
        public IActionResult Edit(Club club)
        {
            if (ModelState.IsValid)
            {
                var dbCLub = _repository.Clubs.FirstOrDefault(c => c.Id == club.Id);
                if (dbCLub != null)
                    (_repository.Clubs as List<Club>)![_repository.Clubs.ToList().IndexOf(dbCLub)] = club;
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Countries = _repository.Scenarios;
            return View(club);
        }
    }
}

Controllers/ScenarioInstanceController.cs
using Microsoft.AspNetCore.Mvc;
using UEFASwissFormatSelector.Models;
using UEFASwissFormatSelector.Services;
using UEFASwissFormatSelector.ViewModels;

namespace UEFASwissFormatSelector.Controllers
{
    public class ScenarioInstanceController : Controller
    {
        private readonly IRepository repository;
        private readonly IMatchDrawService matchDrawService;

        public ScenarioInstanceController(IRepository repository, IMatchDrawService matchDrawService)
        {
            this.repository = repository;
            this.matchDrawService = matchDrawService;
        }        
        [HttpGet]
        public IActionResult Index()
        {
            return View(repository.ScenarioInstances);
        }
        [HttpGet]
        public IActionResult Add(Guid scenarioId)
        {
            var scenario = repository.Scenarios.FirstOrDefault(s => s.Id == scenarioId);
            if (scenario == null)
                return RedirectToAction(nameof(Index), nameof(Scenario));
            var viewModel = new AddScenarioInstanceViewModel();
            viewModel.Scenario = scenario;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Add(AddScenarioInstanceViewModel instanceVM)
        {
            if (ModelState.IsValid)
            {
                var scenario = repository.Scenarios.FirstOrDefault(s => s.Id == instanceVM.Scenario.Id);
                if (scenario == null)
                    return RedirectToAction(nameof(Index), nameof(Scenario));
                var instance = new ScenarioInstance(scenario)
                {
                    Name = instanceVM.Name
                };
                (repository.ScenarioInstances as List<ScenarioInstance>)?.Add(instance);
                return RedirectToAction(nameof(Index));
            }
            return View(instanceVM);
        }
        [HttpGet]
        public IActionResult Edit(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            var viewModel = new EditScenarioInstanceViewModel
            {
                InstanceId = scenarioInstance.Id,
                Scenario = scenarioInstance.Scenario,
                Name = scenarioInstance.Name
            };
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(EditScenarioInstanceViewModel instanceVM)
        {
            if (ModelState.IsValid)
            {
                var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == instanceVM.InstanceId);
                if (scenarioInstance != null)
                    scenarioInstance.Name = instanceVM.Name;
                return RedirectToAction(nameof(Index));
            }
            return View(instanceVM);
        }
        [HttpGet]
        //public IActionResult Explore(Guid scenarioInstanceId, ExploreScenarioInstanceViewModel? vm = null)
        //{
        //    var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
        //    if (scenarioInstance == null)
        //        return RedirectToAction(nameof(Index));
        //    ExploreScenarioInstanceViewModel viewModel;
        //    if (vm == null)
        //    {
        //        viewModel = GenerateVM(scenarioInstance);
        //    }
        //    else
        //    {
        //        viewModel = vm as ExploreScenarioInstanceViewModel;
        //    }

        //    return View(viewModel);
        //}
        public IActionResult Explore(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            var viewModel = new ExploreScenarioInstanceViewModel
            {
                Id = scenarioInstance.Id,
                Scenario = scenarioInstance.Scenario,
                Name = scenarioInstance.Name,
                ClubsInScenarioInstance = scenarioInstance.ClubsInScenarioInstance,
                Pots = scenarioInstance.Pots,
                Opponents = scenarioInstance.Opponents,
                MatchUps = scenarioInstance.MatchUps,
                MatchUpSkeleton = scenarioInstance.MatchUpSkeleton
            };
            if (!viewModel.ClubsInScenarioInstance.Any(c => c == null))
                foreach (var club in viewModel.ClubsInScenarioInstance)
                {
                    club.Club = repository.Clubs.FirstOrDefault(c => c.Id == club.ClubId);
                }
            return View(viewModel);
        }

        //private ExploreScenarioInstanceViewModel GenerateVM(ScenarioInstance scenarioInstance)
        //{
        //    ExploreScenarioInstanceViewModel viewModel = new ExploreScenarioInstanceViewModel
        //    {
        //        Id = scenarioInstance.Id,
        //        Scenario = scenarioInstance.Scenario,
        //        Name = scenarioInstance.Name,
        //        ClubsInScenarioInstance = scenarioInstance.ClubsInScenarioInstance,
        //        Pots = scenarioInstance.Pots
        //    };
        //    if (!viewModel.ClubsInScenarioInstance.Any(c => c == null))
        //        foreach (var club in viewModel.ClubsInScenarioInstance)
        //        {
        //            club.Club = repository.Clubs.FirstOrDefault(c => c.Id == club.ClubId);
        //        }

        //    return viewModel;
        //}

        [HttpGet]
        public IActionResult AddClubs(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            var viewModel = new List<SelectViewModel>();
            foreach (Club club in repository.Clubs)
            {
                viewModel.Add(new SelectViewModel
                {
                    Id = club.Id,
                    Name = club.Name
                });
            }
            ViewBag.scenarioInstanceId = scenarioInstanceId;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddClubs(List<SelectViewModel> selections, Guid scenarioInstanceId)
        {
            if (ModelState.IsValid)
            {
                var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
                if (scenarioInstance == null)
                    return RedirectToAction(nameof(Index));
                var checkedSelections = selections.Where(s => s.IsSelected).ToList();
                int expectedSelections = scenarioInstance.Scenario.NumberOfPot * scenarioInstance.Scenario.NumberOfTeamsPerPot;
                int actualSelections = checkedSelections.Count();
                if (actualSelections != expectedSelections)
                {
                    ViewBag.scenarioInstanceId = scenarioInstanceId;
                    ModelState.AddModelError(string.Empty, $"You have selected {actualSelections} instead of {expectedSelections}");
                    return View(selections);
                }
                var clubsInInstance = new List<ClubInScenarioInstance>();
                foreach (var item in checkedSelections)
                {
                    clubsInInstance.Add( new ClubInScenarioInstance(item.Id, scenarioInstanceId)
                    {
                        Club = repository.Clubs.FirstOrDefault(c=> c.Id == item.Id)
                    });
                }
                scenarioInstance.ClubsInScenarioInstance = clubsInInstance;
                return RedirectToAction(nameof(Explore), new { scenarioInstanceId = scenarioInstanceId });
            }
            return View(selections);
        }
        [HttpGet]
        public IActionResult RankClubs(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            ViewBag.scenarioInstanceId = scenarioInstanceId;
            var viewModel = scenarioInstance.ClubsInScenarioInstance;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult RankClubs(IEnumerable<ClubInScenarioInstance> model, Guid scenarioInstanceId)
        {
            if (ModelState.IsValid)
            {
                var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
                if (scenarioInstance == null)
                    return RedirectToAction(nameof(Index));
                scenarioInstance.ClubsInScenarioInstance = model;
                return RedirectToAction(nameof(Explore), new { scenarioInstanceId = scenarioInstanceId });
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult PotClubs(IEnumerable<ClubInScenarioInstance> model, Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)
                return RedirectToAction(nameof(Index));
            scenarioInstance.Pots = matchDrawService.PotTeam(scenarioInstance);
            return RedirectToAction(nameof(Explore), new { scenarioInstanceId = scenarioInstanceId });
        }
        [HttpGet]
        public IActionResult GenerateOponents(Guid scenarioInstanceId)
        {
            var scenarioInstance = repository.ScenarioInstances.FirstOrDefault(s => s.Id == scenarioInstanceId);
            if (scenarioInstance == null)

Views/ScenarioInstance/Add.cshtml
@model AddScenarioInstanceViewModel
@{
    ViewData["Title"] = $"New {Model.Name} Simulation";
}

<form asp-action="Add" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input asp-for="Scenario.Id" class="form-control" hidden/>
    <div class="mb-3 row">
        <label asp-for="Name" class="col-sm-1 col-form-label">Simulation</label>
        <div class="col-sm-2">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.Name" class="col-sm-1 col-form-label">Scenario</label>
        <div class="col-sm-2">
            <input asp-for="Scenario.Name" class="form-control" readonly />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.HomeAndAwayPerOpponent" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1 form-check mt-auto">
            <input asp-for="Scenario.HomeAndAwayPerOpponent" class="form-check-input bg-primary" disabled />
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="Scenario.NumberOfTeamsPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="Scenario.NumberOfTeamsPerPot" class="form-control" readonly />
            <span asp-validation-for="Scenario.NumberOfTeamsPerPot" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.NumberOfGamesPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="Scenario.NumberOfGamesPerPot" class="form-control" readonly />
            <span asp-validation-for="Scenario.NumberOfGamesPerPot" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.NumberOfPot" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="Scenario.NumberOfPot" class="form-control" readonly />
            <span asp-validation-for="Scenario.NumberOfPot" class="text-danger"></span>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Start Simulation</button>
    </div>
</form>

Views/ScenarioInstance/AddClubs.cshtml
@model List<SelectViewModel>
@{
    ViewData["Title"] = $"Add clubs to Simulation";
}

@if (Model == null || Model.Count() == 0)
{
    <h5>No clubs to display at the moment. <a asp-controller="Club" asp-action="Add">Try adding club.</a></h5>
}
else
{
    <form method="post" asp-route-scenarioInstanceId="@ViewBag.scenarioInstanceId">
        <div asp-validation-summary="All" class="text-danger"></div>
        @for (int i = 0; i < Model.Count(); i++)
        {
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].Id" />
                    <input type="hidden" asp-for="@Model[i].Name" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].Name
                    </label>
                </div>
            }
        }
        <div>
            <button type="submit" class="btn btn-primary">Add clubs</button>
        </div>
    </form>
    
}

Views/ScenarioInstance/Edit.cshtml
@model EditScenarioInstanceViewModel
@{
    ViewData["Title"] = $"Rename {Model.Name} Simulation";
}

<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input asp-for="InstanceId" class="form-control" hidden />
    <div class="mb-3 row">
        <label asp-for="Name" class="col-sm-1 col-form-label">Simulation</label>
        <div class="col-sm-2">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.Name" class="col-sm-1 col-form-label">Scenario</label>
        <div class="col-sm-2">
            <input asp-for="Scenario.Name" class="form-control" readonly />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.HomeAndAwayPerOpponent" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1 form-check mt-auto">
            <input asp-for="Scenario.HomeAndAwayPerOpponent" class="form-check-input bg-primary" disabled />
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="Scenario.NumberOfTeamsPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="Scenario.NumberOfTeamsPerPot" class="form-control" readonly />
            <span asp-validation-for="Scenario.NumberOfTeamsPerPot" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.NumberOfGamesPerPot" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="Scenario.NumberOfGamesPerPot" class="form-control" readonly />
            <span asp-validation-for="Scenario.NumberOfGamesPerPot" class="text-danger"></span>
        </div>
        <label asp-for="Scenario.NumberOfPot" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-1">
            <input asp-for="Scenario.NumberOfPot" class="form-control" readonly />
            <span asp-validation-for="Scenario.NumberOfPot" class="text-danger"></span>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Rename</button>
    </div>
</form>

Views/ScenarioInstance/Explore.cshtml
@model ExploreScenarioInstanceViewModel
@{
    ViewData["Title"] = $"Explore {Model.Scenario.Name}-{Model.Name} Simulation";
}

@if (Model.NoClubInScenarioInstance@* Model.ClubsInScenarioInstance == null || Model.ClubsInScenarioInstance.Count() == 0 || Model.ClubsInScenarioInstance.Any( c=> c== null) *@)
{
    //clubs not added to scenarioInstance yet
    <h5>No clubs in this Simulation yet</h5>
    <a class="btn btn-primary" asp-action="AddClubs" asp-route-scenarioInstanceId="@Model.Id">Add Clubs</a>
}
else
{
    if (Model.ClubsCanBePotted@* Model.Pots.Any(p => p == null) || Model.Pots.Count() == 0 *@ @* || Model.Pots.Any(c => c.ClubsInPot == null) *@)    //clubs have not been potted
    {
        //clubs added but not potted yet
        <h5>Clubs in @Model.Name are</h5>

        int sn = 1;
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Club</th>
                    <th>Ranking</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var club in Model.ClubsInScenarioInstance)
                {
                    <tr>
                        <td>@(sn++)</td>
                        <td>@club.Club?.Name</td>
                        <td>@club.Ranking</td>
                    </tr>
                }
            </tbody>
        </table>
        @if (Model.ClubsNotPotted)
        {
            <span>
                <p>
                    <a asp-action="RankClubs" asp-route-scenarioInstanceId="@Model.Id" class="btn btn-primary">Rank these teams</a>
                    @if (Model.ClubsInScenarioInstance.Any(cisi => cisi.Ranking > 0))
                    {
                        <form asp-action="PotClubs" asp-route-scenarioInstanceId="@Model.Id" method="post">
                            <span style="display:none" id="confirmPotSpan">
                                <span>This action is irreversible. Are you sure you want to pot these teams?</span>
                                <button type="submit" class="btn btn-danger" style="Width:auto">Yes</button>
                                <a class="btn btn-primary" style="Width:auto" onclick="confirmPot(false)">No</a>
                            </span>
                            <span id="potSpan">
                                <a href="#" class="btn  btn-danger" onclick="confirmPot(true)">Pot teams</a>
                            </span>
                        </form>
                    }
                </p>
            </span>
        }        
    }
    if (Model.ClubOpponentsCanBeGenerated @* Model.Pots.Any(c => c.ClubsInPot != null) && Model.Opponents == null *@)     //clubs have been potted
    {
        foreach (var pot in Model.Pots)
        {
            int i = 1;
            <h5>Clubs in @pot.Name</h5>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Club</th>
                        <th>Country</th>
                        <th>***</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ClubInPot cip in pot.ClubsInPot)
                    {
                        <tr>
                            <td>@(i++)</td>
                            <td>@cip.Club?.Name</td>
                            <td>@cip.Club?.Country?.Name</td>
                            <td>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        @if (Model.ClubOpponentsNotGenerated)
        {
            <a asp-action="GenerateOponents" asp-route-scenarioInstanceId="@Model.Id" class="btn btn-primary">Generate potential opponents</a>
        }
    }
    if (Model.MatchupsCanBeDecided @* Model.Opponents != null && Model.MatchUps == null *@)
    {
        foreach (var pot in Model.Pots)
        {
            <h5>Possible opponents for Clubs in @pot.Name</h5>
            foreach (var cip in pot.ClubsInPot)
            {
                int i = 1;
                <h6>*** @cip.Club?.Name </h6>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>Club</th>
                            <th>Pot</th>
                            <th>Possible opponents </th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Pot opponentPot in Model.Opponents[cip.ClubId])
                        {
                            <tr>
                                <td>@(i++)</td>
                                <td>@cip.Club?.Name</td>
                                <td>@opponentPot.Name</td>
                                <td>@string.Join(", ", opponentPot.ClubsInPot.Select(cip => cip.Club?.Name).ToList())</td>
                                <td>
                                    @opponentPot.ClubsInPot.ToList().Count()
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }

        }
        @if (Model.MatchupsNotDecided)
        {
            //write logic for going pot to pot and then club to club to display respective opponent for each club from each pot
            <a asp-action="ShowMatchUp" asp-route-scenarioInstanceId="@Model.Id" class="btn btn-primary">Do Matchups</a>
        }        
    }
    if (Model.CanDisplayMatchUp @* MatchUps != null *@)
    {
        foreach (var pot in Model.Pots)
        {
            <h5>Selected opponents for Clubs in @pot.Name</h5>
            int i = 1;
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Club</th>
                        <th>Selected opponents </th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var cip in pot.ClubsInPot)
                    {
                        var opponents = Model.MatchUps[cip.ClubId];
                        <tr>
                            <td>@(i++)</td>
                            <td>@cip.Club?.Name</td>
                            <td>@string.Join(", ", opponents.Select(club => $"{club.Name} ({club.Country?.Abbrevation}_{Model.Pots.FirstOrDefault(p => p.ClubsInPot.Any(c => c.ClubId == club.Id))?.Name}) ({Model.GetFixtureLocation( Model.MatchUpSkeleton?[cip.ClubId][Model.MatchUps[cip.ClubId].IndexOf(club)].Split('_')[2]) }) ").ToList())</td>
                            <td>
                                @opponents.ToList().Count()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        }
    }
}

@* else
{
    <h5>No provison for this</h5>
} *@

Views/ScenarioInstance/Index.cshtml
@model IEnumerable<ScenarioInstance>
@{
    ViewData["Title"] = "All Scenario Simulations";
}

@if (Model != null && Model.Count() > 0)
{
    int i = 1;
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>SN</th>
                <th>Scenario</th>
                <th>Instance</th>
                <th>Pots</th>
                <th>Teams per pot</th>
                <th>Games per pot</th>
                <th>Home and Away</th>
                <th>***</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var instance in Model)
            {
                <tr>
                    <td>@(i++)</td>
                    <td>@instance.Scenario.Name</td>
                    <td>@instance.Name</td>
                    <td>@instance.Scenario.NumberOfPot</td>
                    <td>@instance.Scenario.NumberOfTeamsPerPot</td>
                    <td>@instance.Scenario.NumberOfGamesPerPot</td>
                    <td>@(instance.Scenario.HomeAndAwayPerOpponent ? "Yes" : "No")</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-scenarioInstanceId="@instance.Id">Rename</a>
                        <a class="btn btn-primary" asp-action="Explore" asp-route-scenarioInstanceId="@instance.Id">Explore</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4>No simulation to display at the moment</h4>
}

Views/ScenarioInstance/RankClubs.cshtml
@model List<ClubInScenarioInstance>
@{
    ViewData["Title"] = $"Rank clubs";
}
<form method="post" asp-route-scenarioInstanceId="@ViewBag.scenarioInstanceId">
    <div asp-validation-summary="All" class="text-danger"></div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>SN</th>
                <th>Name</th>
                <th>Ranking</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count(); i++)
            {
                <tr>
                    <input asp-for="@Model[i].ClubId" class="form-control" hidden />
                    <input asp-for="@Model[i].Club" class="form-control" hidden />
                    <input asp-for="@Model[i].ScenarioInstanceId" class="form-control" hidden />
                    <input asp-for="@Model[i].ScenarioInstance" class="form-control" hidden />
                    <input asp-for="@Model[i].!Club.Name" hidden />
                    <td>@(i+1)</td>
                    <td>@(Model[i].Club?.Name)</td>
                    <td><input asp-for="@Model[i].Ranking" /></td>                    
                </tr>
            }
        </tbody>
    </table>
    <div>
        <button type="submit" class="btn btn-primary">Save ranking</button>
    </div>
</form>